### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck-jekyll-theme#2]
This is a list of requirements that we have

## To be discussed

- [ ] cookies other than standard cookies set by the server?
- [ ] google analytics?
- [x] interactive using javascript?
- [x] #4 - responsive grid layout - which framework bootstrap, foundation, bulma, materialize, other?
- [ ] standard or material design?
- [ ] search - embedded search index (bad for mobile) or google site search?
- [ ] overall design
- [ ] colors
- [ ] typography/fonts
- [ ] assets
- [ ] license? Apache2?
- [ ] do we have a blog?

## Preliminary

- [x] #1 - establish barebone version of theme

## Layout

- [x] default layout for all pages featuring a topbar and a navbar
- [x] guide specific layout derived from default, featuring a guide specific sidebar
- [x] reference specific layout derived from default, featuring a reference specific sidebar
- [x] contribution specific layout derived from default, featuring a contribution specific sidebar
- [x] standard page layout without sidebar

## Navigation

- [x] topbar: search, ?
- [x] navbar: links to Home, Guides, Reference, Contribution, Support... ?
- [x] sidebar: configurable items/links via data descriptors

## Assets

- [ ] logo in various sizes
- [ ] favicon
- [ ] icons for use with android, ios

## Styles (SASS)

- [x] screen
- [ ] print

## Demo Site

with all the features in place we should include a demo site that shows the potential of the theme
